### Spring properties
# Service registers under this name
spring:
  application:
    name: accounts-microservice


# HTTP Server (Tomcat) Port
server: 
  port: 8082
  servlet:
    context-path: /baedose

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false